language: rust
rust:
  - stable
  - beta 
  - nightly 

os:
  - linux
  - osx

script:
  - cargo build
  - cargo test
  - |
    if [ $TRAVIS_RUST_VERSION == nightly ]; then
      cargo build --features "no_std" &&
      cargo test --features "no_std"
    fi